### ISSUE TITLE
fisher.py: Priors has an unexpected shape

### ISSUE THREAD

**Issue by erobic** [simmimourya1/cyvlfeat#18]
When passing in the priors returned from gmm(), I get this error:

> ValueError('priors has an unexpected shape')

The doc says:

> priors :  [F, N]  `float32` `ndarray`

**Comment by erobic** [comment]
https://github.com/menpo/cyvlfeat/issues/34

**Comment by msminhas93** [comment]
The order in which the gmm function outputs the values is different from that specified in the documentation.
The correct order is means, covars, priors, LL, posteriors.

The fisher funtion should work now.
